name: Continous Committing With Node

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  run_git_with_node:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
            
    - name: GitHub config
      run: |
          git config --global user.email "astromedia0010@gmail.com"
          git config --global user.name "Astropeda" 
    - name: Run Node
      run: node git.js
